{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ include "observability.namespace" . }}
  labels:
    app: promtail
    {{- include "observability.labels" . | nindent 4 }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki.{{ include "observability.namespace" . }}.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: {{ join "|" .Values.logNamespaces }}
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: keep
            regex: ${HOSTNAME}
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: __host__
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_name
              - __meta_kubernetes_pod_uid
            separator: _
            target_label: __tmp_pod_dir
          - action: replace
            source_labels:
              - __tmp_pod_dir
              - __meta_kubernetes_pod_container_name
            separator: /
            target_label: __path__
            replacement: /var/log/pods/$1/$2/*.log
{{- end }}
