{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: {{ include "observability.namespace" . }}
  labels:
    app: promtail
    {{- include "observability.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-{{ .Release.Name }}
  labels:
    app: promtail
    {{- include "observability.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [nodes, nodes/proxy, services, endpoints, pods]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-{{ .Release.Name }}
  labels:
    app: promtail
    {{- include "observability.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: {{ include "observability.namespace" . }}
{{- end }}
