name: Demo Manual Approval

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    env:
      ENV: ${{ inputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to ${{ inputs.env }}
        run: |
          echo "Deploying to ${{ inputs.env }} environment"